= Simple Kafka
:sectnums:

This demonstrates a Kafka Producer and Consumer within a single SpringBoot application.

* The Kafka messages are in AVRO format.
* The application by default accesses a Kafka cluster on localhost:9092.
* By default, the application starts its own embedded Kafka broker. If
the port 9092 is already in use, the application will not start its own
broker, but connect to the existing one.
* Optionally a full Kafka broker can be run via docker compose.

== Start the application

....
./gradlew bootRun
....

=== Start the application on a specific port

....
./gradlew bootRun --args='--server.port=8081'
....

== Access the application

=== springdoc-ui

In order to send messages the REST API can be used via UI here:

link:http://localhost:8080/swagger-ui/index.html#/[role=resource,window=_blank]

=== Controlling the listener

// [cols=",",options="header",]
|===
|Action | HTTP Method | URL
|Seek back 10 minutes|GET | link:http://localhost:8080/consumer/seek-back/PT10M[role=resource,window=_blank]
|Seek back to the beginning|GET | link:http://localhost:8080/consumer/seek-to-beginning[role=resource,window=_blank]
|Seek back to the end|GET | link:http://localhost:8080/consumer/seek-to-end[role=resource,window=_blank]
|===

=== Show a JSON message as an AVRO hexdump

Using: link:https://httpie.io/[httpie,role=resource,window=_blank]

....
http --json POST http://localhost:8080/avro/schema/user1/hexdump \
    id=dff964a6-7f97-49da-8eb5-108701e1e3b3 name="Maria do Carmo Mão de Ferro e Cunha de Almeida Santa Rita Santos Abreu" age:=33
....

Using curl:
....
curl -X 'POST' 'http://localhost:8080/avro/schema/user1/hexdump' \
  -H 'Content-Type: application/json' \
  -d '{"id":"dff964a6-7f97-49da-8eb5-108701e1e3b3",name":"Maria do Carmo Mão de Ferro e Cunha de Almeida Santa Rita Santos Abreu","age":33}'
....

== Running a Kafka cluster, Kafdrop and CMAK (Cluster Manager for Apache Kafka)

This requires the "simple-kafka" application to be stopped beforehand,
as it would have started the embedded broker already.

....
docker compose up -d
....

=== Access Kafdrop

Open: link:http://localhost:9006/[role=resource,window=_blank]

=== Access CMAK

. Open: link:http://localhost:9000/[role=resource,window=_blank]
. Only the first time, Cluster/"Add Cluster":
* Cluster Name: Cluster1
* Cluster Zookeeper Hosts: localhost:2181
